title: "Sébastien Gomé"
name: "Sébastien Gomé"
description: "Theoretical researcher in geophysical and statistical fluid dynamics"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

markdown: kramdown
kramdown:
  math_engine: mathjax

collections:
  posts:
    output: false

header:
  nav:
    - title: "Research"
      url: /research/
    - title: "Publications"
      url: /publications/
    - title: "Teaching"
      url: /teaching/
    - title: "CV"
      url: /cv/
    - title: "Contact"
      url: /contact/
