title: "Sébastien Gomé"
name: "Sébastien Gomé"
description: "Research in turbulence, geophysical flows, and statistical fluid mechanics."

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

markdown: kramdown
kramdown:
  math_engine: mathjax

collections:
  posts:
    output: false


