title: "Sébastien Gomé"
name: "Sébastien Gomé"
description: "Theoretical fluid dynamics. Turbulence, geophysical flows, and statistical hydrodynamics."

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  
markdown: kramdown
kramdown:
  math_engine: mathjax

collections:
  posts:
    output: false

locale: en-US


